name: Tests PR Python

on:
  push:
    branches: [main, release]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "5 2 * * 3"
  workflow_dispatch:

jobs:
  Library:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: gautamkrishnar/keepalive-workflow@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # caching pip dependencies
      - name: Install OS-agnostic dependencies
        run: |
          python -m pip install -U pip
          pip install .[testing]
      - name: Install MacOS dependencies
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install libomp
          brew install libmagic
      - name: Install Windows dependencies
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          pip install python-magic-bin
      - name: Install Linux dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install libmagic1
      - name: Test with pytest
        run: |
          python -m pytest -vvvs --durations=50
